language: cpp
os: linux
compiler: gcc

cache:
- directories:
  - $HOME/.cache

addons:
  apt:
    packages: lcov

before_script:
- mkdir -p build && cd build

install:
# (fake) install dependencies
- mkdir -p $HOME/.cache
- touch $HOME/.cache/mydepency.cpp

script:
- cmake -DCODE_COVERAGE=ON ..
- cmake --build . --config Debug -- -j $(nproc)
- ctest -j $(nproc) --output-on-failure

after_success:
# Create lcov report
- lcov --directory . --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info '/usr/*' '*/tests/*' "${HOME}"'/.cache/*' --output-file coverage.info # filter out system
- lcov --list coverage.info
# Uploading to CodeCov
# '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

notifications:
  email:
    - kosrok97@gmail.com
